//user Actions
export const SET_USER = 'SET USER';
export const REMOVE_USER = 'REMOVE USER';

export const SET_AUTHENTICATED = 'SET AUTHENTICATED';

//candidate Actions
export const SET_CANDIDATE = 'SET CANDIDATE';

export const SET_QUIZ = 'SET QUIZ';

export const SET_CANDIDATE_EMAIL = 'SET CANDIDATE EMAIL';

export const SET_REMAINING_TIME = 'SET_REMAINING_TIME';

export const SET_PREVIOUS_PATH = 'SET PREVIOUS PATH';

export const SET_CURRENT_PAGE = 'SET CURRENT PAGE';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const SET_VALID = 'SET VALID';
export const SET_VERIFIED = 'SET VERIFIED';
export const SET_CODE_SENT = 'SET CODE SENT';

export const SET_DISQUALIFIED = 'SET DISQUALIFIED';

export const SET_STARTED= 'SET STARTED';
export const SET_FINISHED = 'SET FINISHED';

export const SET_QUESTION_NUMBER= 'SET QUESTION NUMBER';
export const INCREMENT_QUESTION_NUMBER= 'INCREMENT QUESTION NUMBER';

export const UPDATE_POINTS = 'UPDATE_POINTS';

